import { createRequire } from "module";
import type { Response } from "express";
import type { IOrder } from "../models/order.model.js";

const require = createRequire(import.meta.url);
// pdfkit is CJS with `export =` — must use createRequire in ESM/nodenext context
const PDFDocument = require("pdfkit") as typeof import("pdfkit");

type PopulatedOrderedBy = {
  firstName: string;
  lastName: string;
  email: string;
};

function formatNOK(amount: number): string {
  return `${amount.toLocaleString("nb-NO")} kr`;
}

function formatDate(date: Date): string {
  return new Date(date).toLocaleDateString("nb-NO", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

export const generateInvoicePdf = (order: IOrder, res: Response): void => {
  const orderedBy = order.orderedBy as unknown as PopulatedOrderedBy;

  const doc = new PDFDocument({ margin: 50, size: "A4" });
  doc.pipe(res);

  // ─── Header ───────────────────────────────────────────────────────────────
  doc
    .fontSize(24)
    .font("Helvetica-Bold")
    .text("INVOICE", 50, 50);

  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#666666")
    .text(`Reference: ${order._id}`, 50, 82)
    .text(`Date: ${formatDate(order.createdAt)}`, 50, 96);

  // ─── Bill To ──────────────────────────────────────────────────────────────
  doc
    .moveTo(50, 130)
    .lineTo(545, 130)
    .strokeColor("#e0e0e0")
    .stroke();

  doc
    .fontSize(10)
    .font("Helvetica-Bold")
    .fillColor("#000000")
    .text("BILL TO", 50, 145);

  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#333333")
    .text(order.companyName, 50, 162)
    .text(`Org. number: ${order.orgNumber}`, 50, 176);

  if (orderedBy) {
    doc
      .text(`${orderedBy.firstName} ${orderedBy.lastName}`, 50, 190)
      .text(orderedBy.email, 50, 204);
  }

  // ─── Campaign name ────────────────────────────────────────────────────────
  doc
    .moveTo(50, 230)
    .lineTo(545, 230)
    .strokeColor("#e0e0e0")
    .stroke();

  doc
    .fontSize(10)
    .font("Helvetica-Bold")
    .fillColor("#000000")
    .text("CAMPAIGN", 50, 245);

  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#333333")
    .text(order.campaignName, 50, 260);

  // ─── Line items table ─────────────────────────────────────────────────────
  doc
    .moveTo(50, 286)
    .lineTo(545, 286)
    .strokeColor("#e0e0e0")
    .stroke();

  // Table header
  doc
    .fontSize(10)
    .font("Helvetica-Bold")
    .fillColor("#000000")
    .text("DESCRIPTION", 50, 300)
    .text("AMOUNT", 450, 300, { width: 95, align: "right" });

  doc
    .moveTo(50, 316)
    .lineTo(545, 316)
    .strokeColor("#e0e0e0")
    .stroke();

  // Table rows
  let y = 328;
  const lineItems = order.lineItems ?? [];

  for (const item of lineItems) {
    const label =
      item.type === "package"
        ? `${item.name.charAt(0).toUpperCase() + item.name.slice(1)} package`
        : item.name.charAt(0).toUpperCase() + item.name.slice(1);

    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#333333")
      .text(label, 50, y)
      .text(formatNOK(item.price), 450, y, { width: 95, align: "right" });

    y += 20;
  }

  // ─── Totals ───────────────────────────────────────────────────────────────
  y += 10;
  doc
    .moveTo(50, y)
    .lineTo(545, y)
    .strokeColor("#e0e0e0")
    .stroke();

  y += 14;

  const vatRate = order.vatRate ?? 0.25;

  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#333333")
    .text("Subtotal", 350, y)
    .text(formatNOK(order.subtotal), 450, y, { width: 95, align: "right" });

  y += 18;

  doc
    .text(`VAT (${Math.round(vatRate * 100)}%)`, 350, y)
    .text(formatNOK(order.vatAmount), 450, y, { width: 95, align: "right" });

  y += 18;

  doc
    .moveTo(350, y)
    .lineTo(545, y)
    .strokeColor("#000000")
    .stroke();

  y += 10;

  doc
    .fontSize(11)
    .font("Helvetica-Bold")
    .fillColor("#000000")
    .text("Total", 350, y)
    .text(formatNOK(order.totalAmount), 450, y, { width: 95, align: "right" });

  // ─── Footer ───────────────────────────────────────────────────────────────
  doc
    .fontSize(9)
    .font("Helvetica")
    .fillColor("#999999")
    .text("Generated by JobPulse", 50, 760, { align: "center", width: 495 });

  doc.end();
};
